
classDiagram
    class Disc {
        -x: float
        -y: float
        -radius: float
        +__init__(x: float, y: float, radius: float)
        +get_area(other: Disc) float
    }

    Disc --> Disc
