quadrantChart
    title "Efficiency and Scalability of Set Operations Solutions"
    x-axis "Low Efficiency" --> "High Efficiency"
    y-axis "Low Scalability" --> "High Scalability"
    quadrant-1 "We should expand"
    quadrant-2 "Need to promote"
    quadrant-3 "Re-evaluate"
    quadrant-4 "May be improved"
    "Solution A": [0.3, 0.6]
    "Solution B": [0.45, 0.23]
    "Solution C": [0.57, 0.69]
    "Our Target Product": [0.5, 0.6]